### ISSUE TITLE
northbound API definition in OpenAPI specification is out of dated.

### ISSUE THREAD

**Issue by itaru2622** [openalto/alto#45]
current northbound API provided by src/alto/server/northbound/*  has more interfaces and different than openalto/alto-swagger repo.

It's better to provide/generate openapi spec of northbound API in code-first manner from src/alto/server/northbound/*.

**Comment by fno2010** [comment]
Nice proposal. Actually, the `openalto/alto-swagger` repo is quite old. When it was created 6 years ago, OpenAPI 3.0 was still not very mature. The `patternProperties` feature was not supported by most of the code generators. But many ALTO services highly rely on this feature.

I see the latest code generator may support `patternProperties` better. We can try to see if it is possible to integrate OpenAPI into openalto.

**Comment by fno2010** [comment]
I feel the `openalto/alto-jsonschema` repo may be more useful than `openalto/alto-swagger`.
